version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - ELASTIC_PASSWORD=1234
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9199:9200"
      - "9299:9300"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: interview
    ports:
      - "3501:3306"
  redis_container:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6397:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf