services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=1234'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200'
      - '9300'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=interview'
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - '3306:3306'
  redis_container:
    image: redis:latest
    container_name: redis_dev
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf