### 회원가입을 먼저 진행해주세요.
POST localhost:8901/authorities/sign-up
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password",
  "confirmPassword": "password"
}


### 실행하기 전 먼저 회원가입을 진행해주세요.
POST localhost:8901/authorities/sign-in
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}