###
POST localhost:8901/authority/sign-up
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password",
  "confirmPassword": "password"
}


###
POST localhost:8901/authority/sign-in
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}