###
GET localhost:8901/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImV4cCI6MTY5ODgxMjM1NiwiYXV0aCI6IltST0xFX01FTUJFUl0ifQ.uQdXSXt9Foiu_z93c8jTRK1AMgFszXKgFl1j7oTSAaM

{
  "questionTypes": [
    "DATABASE", "NETWORK"
  ],
  "programingTypes": [
    "JAVA", "KOTLIN"
  ],
  "frameworkTypes": [
    "SPRING"
  ],
  "levels": [
    1, 3
  ]
}

###
GET localhost:8901/question/position/BACKEND
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImV4cCI6MTY5ODgxMjM1NiwiYXV0aCI6IltST0xFX01FTUJFUl0ifQ.uQdXSXt9Foiu_z93c8jTRK1AMgFszXKgFl1j7oTSAaM

###
GET localhost:8901/question/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImV4cCI6MTY5ODgxMjM1NiwiYXV0aCI6IltST0xFX01FTUJFUl0ifQ.uQdXSXt9Foiu_z93c8jTRK1AMgFszXKgFl1j7oTSAaM
