spring:
  application:
    name: iterview
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://host.docker.internal:3501/iterview
    username: name
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://host.docker.internal:3501/iterview
    user: name
    password: password

  sql:
    init:
      mode: never
      data-locations:
        - classpath:sql/*.sql
        - classpath:sql/framework/*.sql
        - classpath:sql/programing/*.sql

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      host: host.docker.internal
      port: 6397

  cache: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: email
    password: password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8901

api-key: your-api-key

jwt:
  header: Authorization
  secret: your-secret-key
  token-validity-in-seconds: 10800
  refresh-token-validity-in-seconds: 86400
