spring:
  application:
    name: gpt-interview
  datasource:
    url: jdbc:mysql://mysql:3501/interview
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
      init:
        mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false
server:
  port: 8901

api-key: your-open-ai-api-key

jwt:
  header: Authorization
  secret: your-secret-jwt-key
  token-validity-in-seconds: 10800
  refresh-token-validity-in-seconds: 86400