# review: flyway 를 사용해서 형상 관리를 해보는건 어떨까요? 현 상황에서는 문제가 추가되면 데이터를 다시 날린다음 넣어야 할거 같네요
spring:
  application:
    name: iterview

  datasource:
    url: jdbc:mysql://mysql:3501/iterview
    username: your-username
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://mysql:3501/iterview
    user: cherhy
    password: wjd0322189!

  sql:
    init:
      mode: always
      data-locations:
        - classpath:sql/*.sql
        - classpath:sql/framework/*.sql
        - classpath:sql/programing/*.sql

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6397

  cache: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email
    password: your-password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8901

api-key: your-open-ai-api-key

jwt:
  header: Authorization
  secret: your-jwt-secret-key
  token-validity-in-seconds: 10800
  refresh-token-validity-in-seconds: 86400
