spring:
  application:
    name: iterview

  cache: redis

  config:
    activate:
      on-profile: local

  datasource:
    url: ENC(ISGU4B0SIGBjotonifvJCiL2wirwWiFDEP16ZGB0w6yaWSAXycng7XF1ZzYo36Ew)
    username: ENC(2JA6lbC9M3tzp5CnvJg3rg==)
    password: ENC(DhGziWvTVdnlS3fzhvP2UjzuCX3ZfpKS)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      host: ENC(ylOXhuRJ+nOtc0Za/RiBFqFr9v2cCpig)
      port: ENC(5FiIEpTUFLoBGGmI3Vx9Gg==)

  mail:
    host: ENC(Mz2+M9eFGsqmIa8XrhwB2ZjrP+7zeBdZ)
    port: ENC(StcEUTdFCzwO3w4w5I0ABQ==)
    username: ENC(M4F2BtuCfc2iTb2wn8P+ylUpCQ1ZJqg3/EAj2U5NCmA=)
    password: ENC(cBUbprMjnyXe2CkseVhLT2tSWy+HVEsN0UJchFaOheU=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8901

gpt:
  api-key: ENC(TR7PE9Ncamxwvl/hanmuE7DHjnRswd/3sJi8iFtCRyZ8TXAs6WSPEcOEMoZM+kSpyXDWN1iBD5ma2Ot0f4O/Rw==)
  model: ENC(U5Z2m9/IipwgqjIWefT2CJiadkGJoIPuOuBq3WN1aj8=)
  max-tokens: ENC(1MLX7nSkPYavGaJYKLfqNA==)
  temperature: ENC(5hoVArJA1nMBafn9QVQYCg==)

jwt:
  secret: ENC(5GHnPZIF7LWtLVhNHbeD+MU31NiytSHXKjA94xsVeSB8DGqHqerc4wi6jcRDH0Qu8iNZmyJh1I6qWOJU3e4HD8zqRAR+ehpbS3twM7mREvhX9SH1HnyHfXuhH0P2JJUcLEpWE8ZExSmfQXkzGtuM8k6X0fxp6m2dxTOS3uK1aX0dHPQSQCxUXn2GDM/GHp2t)
  algorithm: ENC(lW5OyGlhGPu+V4mqQKZrwUwxk4zZlW2p)
  token-validity-in-seconds: ENC(x1wKzd7lHKdnfrD5uUwAnA==)
  refresh-token-validity-in-seconds: ENC(9pEjw+Ss6ONot60OrzgLhQ==)
  authority-key: ENC(uUdyCzQpsDZuSx6I+4N6tw==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor