spring:
  application:
    name: iterview

  cache: redis

  config:
    activate:
      on-profile: local

  datasource:
    url: ENC(ISGU4B0SIGBjotonifvJCiL2wirwWiFDEP16ZGB0w6yaWSAXycng7XF1ZzYo36Ew)
    username: ENC(2JA6lbC9M3tzp5CnvJg3rg==)
    password: ENC(DhGziWvTVdnlS3fzhvP2UjzuCX3ZfpKS)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      host: ENC(ylOXhuRJ+nOtc0Za/RiBFqFr9v2cCpig)
      port: ENC(5FiIEpTUFLoBGGmI3Vx9Gg==)

  mail:
    host: ENC(Mz2+M9eFGsqmIa8XrhwB2ZjrP+7zeBdZ)
    port: ENC(StcEUTdFCzwO3w4w5I0ABQ==)
    username: ENC(1/5Lr19WTv1Xoc90Tj5wyxSL9U5Y/Mcff6T8iMvrCkI=)
    password: ENC(cBUbprMjnyXe2CkseVhLT2tSWy+HVEsN0UJchFaOheU=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8901

gpt:
  api-key: ENC(TR7PE9Ncamxwvl/hanmuE7DHjnRswd/3sJi8iFtCRyZ8TXAs6WSPEcOEMoZM+kSpyXDWN1iBD5ma2Ot0f4O/Rw==)
  model: ENC(U5Z2m9/IipwgqjIWefT2CJiadkGJoIPuOuBq3WN1aj8=)
  max-tokens: ENC(1MLX7nSkPYavGaJYKLfqNA==)
  temperature: ENC(5hoVArJA1nMBafn9QVQYCg==)

jwt:
  secret: ENC(5GHnPZIF7LWtLVhNHbeD+MU31NiytSHXKjA94xsVeSB8DGqHqerc4wi6jcRDH0Qu8iNZmyJh1I6qWOJU3e4HD8zqRAR+ehpbS3twM7mREvhX9SH1HnyHfXuhH0P2JJUcLEpWE8ZExSmfQXkzGtuM8k6X0fxp6m2dxTOS3uK1aX0dHPQSQCxUXn2GDM/GHp2t)
  algorithm: ENC(lW5OyGlhGPu+V4mqQKZrwUwxk4zZlW2p)
  token-validity-in-seconds: ENC(x1wKzd7lHKdnfrD5uUwAnA==)
  refresh-token-validity-in-seconds: ENC(9pEjw+Ss6ONot60OrzgLhQ==)
  authority-key: ENC(uUdyCzQpsDZuSx6I+4N6tw==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

oauth2:
  client:
    google:
      token-uri: ENC(PQwggtxklvEkJ8mCbpGhsVViDGQei9jBxxaIDrUUM/mTOCb6TcWXSxh+QJnIHtUnP0r+VZoqIH0=)
      client-id: ENC(CoS1YQPj4lXOPN2u7SjcrVUur/AS1NhzqNemTGuBrGs=)
      redirect-uri: ENC(4e/XpicF+tpsTpfX1QdltjynH2UhhDK++v6Fo5U2Hpw=)
      client-secret: ENC(dMxOo9bsfT1oSaxL2Pv19nRCkeF5fzB8DirqOs6Ag6k=)
      client-authentication-method: ENC(w2nPpHxELlyBseu63hEUke32214Ja7Mr0CwEZaGnV5I=)
      authorization-grant-type: ENC(/mmL/BJz1aD62/H4zH0qDbcDCuCBrAKeSDayXm0Jnb4=)
      scope: ENC(cSj//Eg478QNdsS436PPfKiftFmnb785ri8DQ4/WJsM=)
      client-name: ENC(btEOk7njA5vwN+pcut1WkWyRjtWOXROeRIOzWlTdA0g=)
    kakao:
      client-id: ENC(frcolbLfPp0QMyK/Qx07NCg+FlQa8bnEtkJxqEBykfO/blb9X59aDTQunes77ZB5)
      redirect-uri: ENC(RdkTSOeN0lne+DEdO+z701ezusm6sVWEYsdyY44/9VZKe4F8Xha5kS73tYbmbP++wrwhCWAFx7U=)
      client-secret: ENC(b5jPe5jDAlaEZm4pJ1eFkpqSOTzK+jLRgpQRtT6M8bpHtlo1reLRXW6rS338mmP4)
      client-authentication-method: ENC(QZ4rhou8QcFCVE8pF5w4Qg==)
      authorization-grant-type: ENC(13tyB06yTYnhhsnRLVaJI1Nee6x6gOyGI7gI64MlNtU=)
      scope: ENC(b7u/j3wRYpYK7JD67x52u4w4SVopqpwbcpobcYfh+rOTjTw5vjkIt4Eh8qxVKgHr2YFE15vR+2U=)
      client-name: ENC(p466ueEXmznujCV3SLlLjQ==)
  provider:
    kakao:
      authorization_uri: ENC(RSvj3e2MQL1SIIPiCMWhlQQeWcv70Sd7I7rOHgMlZ5UYaMx7PMuhE9m4OuJLwUK1)
      token_uri: ENC(dQFcjvT4U3cd5hCCGzYY+DbCq0ZtB8SLhu6MtgS3PwIYnkLhiyXEEjCjvNsh8oNU)
      user-info-uri: ENC(0ZSnOdT93So6nkMV/zFuHi9PgFLpRkCu0K4zzuDo+vKTVmLFV7LlzDaZoh5qd0fR)
      user_name_attribute: ENC(Xmqpsq5A8+AOTpM3LeEMrg==)
  default:
    password: ENC(eq6EnHZlGq1ner+W6F15Zza8OHH1DAsg)
    salt: ENC(Bodekxx7rnjJ1sifihQRBw==)