spring:
  application:
    name: iterview

  cache: redis

  config:
    activate:
      on-profile: dev

  datasource:
    url: ENC(DATABASE_URL)
    username: ENC(DATABASE_USERNAME)
    password: ENC(DATABASE_PASSWORD)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: ENC(DATABASE_URL)
    user: ENC(DATABASE_USERNAME)
    password: ENC(DATABASE_PASSWORD)

  sql:
    init:
      mode: never
      data-locations:
        - classpath:sql/*.sql
        - classpath:sql/framework/*.sql
        - classpath:sql/programing/*.sql

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      host: ENC(REDIS_URL)
      port: ENC(REDIS_PORT)

  mail:
    host: ENC(MAIL_HOST)
    port: ENC(MAIL_PORT)
    username: ENC(MAIL_USERNAME)
    password: ENC(MAIL_PASSWORD)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8901

gpt:
  api-key: ENC(GPT_KEY)

jwt:
  header: Authorization
  secret: ENC(JWT_SECRET)
  token-validity-in-seconds: ENC(JWT_ACCESS_EXPIRATION)
  refresh-token-validity-in-seconds: ENC(JWT_REFRESH_EXPIRATION)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor