spring:
  application:
    name: gpt-interview
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/interview
    username: user
    password: 1234

server:
  port: 8901

api-key: your-open-ai-api-key

jwt:
  header: Authorization
  secret: your-secret-jwt-key
  token-validity-in-seconds: 10800
  refresh-token-validity-in-seconds: 86400