spring:
  application:
    name: iterview

  cache: redis

  config:
    activate:
      on-profile: local

  datasource:
    url: ENC(umsgxoaa8ozCbonhylS5J0Hc0bp83RSNishdaQ52bb7SgDev9SawTNkLSXflkvAF)
    username: ENC(Vr3pVJGGDzxCXt87l/DXLA==)
    password: ENC(JBmJhAuqTJfaBty2ScvI4Wz1jcUAhDpI)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

    redis:
      host: ENC(mS7ThrEwK/ObO95kkxfQVOaIp4AYGD7a)
      port: ENC(/VpBoGDlg3Cee9qZxNMw0Q==)

  mail:
    host: ENC(1hXOFJQq7m8ynSW2a6b1CGmBuZkVeCC3)
    port: ENC(qb/seMi4z6/41EJdatfEAg==)
    username: ENC(9psRfDAoGn4RR0bwfhGQq52Xop2uwe/knpklsrUTTz4=)
    password: ENC(j9j111bVYYhgpRcwCQdVRObLUyztljqjn6blOl39M4E=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

server:
  port: 8901

gpt:
  api-key: ENC(YlIOGmhEAT9AfbG07YKSTPonmTpR2UjPyTIluWgHZIp31Z1QP7YMtROIbtOja5ehDRDmQ76YWiM/EnxpAbfUig==)

jwt:
  secret: ENC(eOfRAmjveMWkNeUcJ5Qyyln3/QndmrARoE2h4fq2Cd/q/CJjnS4o4dob1hB0ypSLtlVZSLyi3izhh54dy88OF6PObuSf/FAOvbF2v+zeYeBKJvWz1JZTy6PlYzsnbgHCpfFd/JRnAl06/1dax75V/Zo6XHTi9+AFiB6C2Yk/1PKqp+rRAAKcx8abujVyUMS5)
  algorithm: ENC(FZP1ocYqbuUNqKTryg4hs9RsnWU71+kg)
  token-validity-in-seconds: ENC(Ve48Jm2889YJ2q+1i0k2Ow==)
  refresh-token-validity-in-seconds: ENC(/QKwo/CreUrMtmwlV8Awdw==)
  authority-key: ENC(UVfqbHMajrR5flVbVmMQtw==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor